// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mazjnttdnendismnxhkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hempudHRkbmVuZGlzbW54aGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzgyNDEsImV4cCI6MjA2NDA1NDI0MX0.J-thIXi3apCvtxop6Zfo8Ahf2l3Xm-6JtpEQZdeTYRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);